Highlighting current user & Support for tourist title
rahulharpal1603/CF-TopHacker pull request #14
Opened 2024-10-09 19:59 UTC by Piyush-Goenka

1. Highlighting the current user's row: When a user is logged in and their name appears in the hacks standings table, their row will be highlighted for easy identification.
2. Support for Tourist title: Users with the title "Tourist" will now be supported, and this title will be displayed appropriately in the standings.
I have checked the changes made in the extension via using developer mode in chrome extension.
I have checked the highlighting part for a random user and it is working finely.
<img width="1729" alt="Screenshot 2024-10-09 at 7 10 22 PM" src="https://github.com/user-attachments/assets/ad2891c4-76c3-46e2-b707-a22b732f8e57">

2024-10-15 05:08 UTC, rahulharpal1603 requested changes

2024-10-15 05:08 UTC, rahulharpal1603 commented on src/content.js
> +  Tourist: "#ff0000",
The tourist title has only the first letter as red, the other letters are black. See the code to handle legendary grandmasters. You have to code that part too. The highlight user row works good.

2024-10-15 05:09 UTC, rahulharpal1603 commented
@Piyush-Goenka please make the changes requested above.

2024-10-15 10:05 UTC, Piyush-Goenka commented
Hey @rahulharpal1603 
I have made the required changes that has been asked in the latest commit.
I have changed the first letter of tourist to red and rest to black.
Thanks for guiding me.

2024-10-15 13:17 UTC, rahulharpal1603 approved these changes

2024-10-17 04:32 UTC, rahulharpal1603 commented
Thank you! @Piyush-Goenka

2024-10-17 04:32 UTC, merged